-- Crear tabla RELACION_DTK
CREATE TABLE RELACION_DTK (
    ID_RELACION RAW(16) PRIMARY KEY,
    ROTULOTK VARCHAR2(255) NOT NULL,
    ID_DISPOSITIVO VARCHAR2(255) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    ESTADO NUMBER(1,0) DEFAULT 1
);

-- Crear tabla MEDICION
CREATE TABLE MEDICION (
    ID RAW(16) PRIMARY KEY,
    NIVEL NUMBER NOT NULL,
    FECHA TIMESTAMP NOT NULL,
    ID_RELACION RAW(16) NOT NULL,
    CONSTRAINT FK_MEDICION_RELACION FOREIGN KEY (ID_RELACION) 
        REFERENCES RELACION_DTK(ID_RELACION)
);