version: '3.8'
services:
  webapp:
    build: .
    container_name: esval-webapp
    ports:
      - "8080:7121"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_USER=<DB_USER_PROVIDED_BY_COMPANY>
      - DB_PASSWORD=<DB_PASSWORD_PROVIDED_BY_COMPANY>
      - DB_SOURCE=<DB_SOURCE_PROVIDED_BY_COMPANY>
