# Usar imagen base de SDK de .NET 8.0 para compilar
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copiar archivo de proyecto y restaurar dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiar resto de archivos y compilar
COPY . ./
RUN dotnet publish -c Release -o out

# Generar imagen de runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .
COPY --from=build-env /app/wwwroot ./wwwroot

EXPOSE 7121
ENTRYPOINT ["dotnet", "EsvalTK.dll"]
